### ISSUE TITLE
Loving it!

### ISSUE THREAD

**Issue by 0xScratch** [Markeljan/web3gpt#3]
Hey @Markeljan,

Well, it's not a real issue just an appreciation of what you did within this project during the backdrop build V4. Truly amazing and loved it to be honest. Before talking more about it, would love to introduce myself...

My name is Aryan, identify myself as a Web3 Enthusiast | Smart Contract Dev and it's not long since I dived into this space. Still learning and building stuff, exploring creative corners, and leveraging upon my skills. Also remained a finalist during Backdrop Build V4 alongside you within 2 projects - [SureYouDo.io](https://backdropbuild.com/builds/v4/sureyoudoio-aind) and [Anyflow](https://backdropbuild.com/builds/v4/anyflow-sxo7). Apart from building, a side activity I do is look for potential projects and appreciate what they did (plus, it also adds to cool ideas, problems, and sometimes even better solutions).

Just a few minutes before, I watched the demo and tried the app out (mainly by creating a smart contract that helps in attestations of luxury items). Also tested whether the AI understands what it is coding or doing, and to the greatest extent it does which is impressive. Coming down to deployments, it was unexpected to see that it deployed the contract and also created an IPFS directory for the same. Loved that feature, kudos to you.

Overall, it's great and as soon I will be participating in an ETHGlobal hackathon, I am considering Web3GPT within my project to pace up the development process for my project (ideation is still in progress, suggestions are welcome!). That's why I have some questions, and it will be great to hear some of your views on how to take the most out of this app.

1. Suppose, I am thinking about developing a smart contract that is a bit complex, then who will perform a better job - Web3GPT or the classic chatGPT? Is there even a difference between them in terms of accuracy, performance, better code understanding, and creativity part? Usually, chatGPT performs well with beginners and sometimes the intermediate level of difficulty when it comes to smart contracts but during the advanced phase, it fucks up.

2. Does it require the user to have a chatGPT Plus subscription? As I saw it uses GPT-4o and GPT-4o-mini which are limited with the free subscription of chatGPT.

3. Just curious to know, does it keep the traces of memories?

That's it! will explore it more from my side. Moreover, subscribed for the early access as it seems worth it...

Also, Congratulations on launching it down and being part of the Bitte Protocol 🎉

Best Regards,
Aryan

**Comment by Markeljan** [comment]
Yo! @0xScratch   That's so awesome for you to drop a message,  great to hear from a fellow builder! 

- It's free, no subscription required but your chat's won't save if you don't login with Github.  Been able to keep it free thanks to Gitcoin / PG funding so far, just got into https://giveth.io/project/web3gpt as well.

- As far as the context / training it is technically only as good as Chat GPT although because it is specializing in Solidity development / Web3 it may seem more reliable.  The memory management is handled by the OpenAi assistants api.  It truncates and summarizes automatically when a chat get's too long.  Messages are also stored in a db / KV storage.

- I've just updated the Agent Creator so that created agents can deploy contracts and use tools just like the main assistants so hoping to see some more specialized solidity agents.  For example this [OpenZeppelin v5 Agent](https://web3gpt.app/?a=asst_s66Y7GSbtkCLHMWKylSjqO7g)

Feel free to reach out on https://t.me/soko_eth 

Thanks for they hype & feedback, keep on buildin 🚀

**Comment by 0xScratch** [comment]
Thanks for the reply and answering my questions @Markeljan 

Will reach out soon on Telegram!
